### ISSUE TITLE
Add site token

### ISSUE THREAD

**Issue by leg100** [leg100/otf-charts#1]
Add option to configure a [site admin](https://docs.otf.ninja/en/latest/#site-admin) token for the helm chart.

**Comment by pat-s** [comment]
Via env var `OTF_SITE_TOKEN`?

**Comment by leg100** [comment]
Yes looks like I added the option some time ago:

https://github.com/leg100/otf-charts/blob/b67fc5368383360fa46c2e68ce5d69728ea3489f/charts/otf/templates/deployment.yaml#L58

I'll close the issue!
