### ISSUE TITLE
A chart for `otf-agent`?

### ISSUE THREAD

**Issue by pat-s** [leg100/otf-charts#14]
Background: we are running OTFD on a single VM to not have it run in the same environment it is mainly responsible for (k8s cluster).

However, to not have a static VM sitting idle for a long period of time, it would be great if the runs could be run via agents on a k8s cluster.

This leads to the idea of having a dedicated chart for `otf-agent` which can accept some agent tokens in it's config (to register with the daemon) and (optionally) also defines some resources.
The latter is of interest as depending on the size of the workspace state, some runs take ~ 1 GB, some just a few MB RAM to run.

All in all this would allow for a distributed execution and make OTF more flexible. If the agents are not reachable, one could still switch to "remote" or "local" runs then.

**Comment by leg100** [comment]
Yes, I think a dedicated chart for `otf-agent` makes sense. Other users have made the same request.

**Comment by pat-s** [comment]
I've created a chart for `otf-agent`: https://github.com/pat-s/otf-agent-helm

I would be fine moving into this repo so users have only one go-to-place for all charts. Let me know what your preferences are 🙂 

It might make sense to also create a chart for `otfd` only and on top an overarching chart which installs both at the same time? Depending on how OTF is installed and use, users might sometimes need both or just one of each.

In my use case I host `otfd` on an external VM and run builds on a k8s cluster.
OTF runs for the cluster itself run via the `remote` option on the external VM.

Maybe the above could also be outlined as one option how to use OTF from an architectural perspective as executing OTF runs on the same base it's being operated on might lead to inaccessibility of the remote state if something doesn't go as planned. 

PS: The chart comes also with another custom image build of ours which bundles `aws` in the agent image - otherwise we wouldn't be able to execute runs on our EKS cluster. [cynkra/otf-agent](https://hub.docker.com/r/cynkra/otf-agent).
