### ISSUE TITLE
Issues setting up database connection

### ISSUE THREAD

**Issue by pat-s** [leg100/otf-charts#2]
Chart: 0.1.11
Image: 0.0.24

I have set `database` to a Postgres connection string, yet the pod returns

```
│ Error: failed to connect to `host=/tmp user=root database=`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)  
```

Which seems like the value is not picked up at all. Is the value actually in use or is the connection determined differently?

**Comment by leg100** [comment]
Can you paste the command you're using to deploy the helm chart? You're right, it's not being picked up.

Might be worth looking at https://github.com/leg100/otf-kind , which shows how the demo env is currently deployed using helmfile.

**Comment by pat-s** [comment]
Not sure if the postgres connection string is correct but even if not, it should return a different error message.

Do you have a test deployment of the helm chart on your side? How do you do it?

```tf
resource "helm_release" "otf" {
  name             = "otf"
  chart            = "otf"
  repository       = "https://leg100.github.io/otf-charts"
  version          = "0.1.11"
  create_namespace = true
  namespace        = "otf"
  timeout          = 90
  count            = 1


  set {
    name  = "ingress.hosts[0].host"
    value = "${var.OTF_DOMAIN}.${var.DNS_DOMAIN}"
  }

  set {
    name  = "ingress.hosts[0].paths[0].path"
    value = "/"
  }

  set {
    name  = "ingress.hosts[0].paths[0].pathType"
    value = "Prefix"
  }

  set {
    name  = "ingress.tls[0].secretName"
    value = "${var.OTF_DOMAIN}.${var.DNS_DOMAIN}-tls"
  }

  set {
    name  = "ingress.tls[0].hosts[0]"
    value = "${var.OTF_DOMAIN}.${var.DNS_DOMAIN}"
  }

  set {
    name  = "database"
    value = "otf:${data.vault_generic_secret.otf-db-pass.data["value"]}@${module.postgres.db_instance_address}:5432/otfdb?sslmode=disable&connect_timeout=10"
  }
  depends_on = [kubernetes_job.otf-init-db, module.cluster_dev]
}
```

**Comment by leg100** [comment]
You need to prefix the database value with `postgres://` in order to make it a legitimate connection string.

https://www.postgresql.org/docs/current/libpq-connect.html

I'll add some validation.

**Comment by leg100** [comment]
Nice, glad it worked.
